openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /appinfo/health/liveness:
    get:
      tags:
        - health-controller
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Health'
  /api/funda/search/municipalities:
    get:
      tags:
        - funda-controller
      operationId: getMunicipalities
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Municipality'
components:
  schemas:
    Health:
      type: object
      properties:
        details:
          type: object
          additionalProperties:
            type: object
    Municipality:
      type: object
      properties:
        date:
          type: string
          format: date-time
        name:
          type: string
        url:
          type: string
        nrOfListings:
          type: integer
          format: int32
